In [1]:
function myadd(x, y, z...)
           if isempty(z)
               return x + y
           end
           return x + myadd(y, z...)
       end


myadd(1,4)
#myadd(1,2,3,4)


5

In [1]:
function change_first_element!(arr::Array{T}, val::T) where {T <: Number} 
    @show T 
    arr[1] = val
end

change_first_element! (generic function with 1 method)

In [2]:
x=zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [3]:
change_first_element!(x, 1)

LoadError: MethodError: no method matching change_first_element!(::Array{Float64,1}, ::Int64)
Closest candidates are:
  change_first_element!(::Array{T,N} where N, !Matched::T) where T<:Number at In[1]:1

In [4]:
change_first_element!(x, 1.0)

T = Float64


1.0

In [5]:
y = ones(3, 3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [8]:
change_first_element!(y, 4.0)

T = Float64


4.0

In [18]:
struct Foo 
       bar 
       baz::Int 
       qux::Float64 
end

In [19]:
foo_3 = Foo(false, 3.4, 2.4)

LoadError: InexactError: Int64(3.4)

In [20]:
foo_3 = Foo(false, 3, 2.4)

Foo(false, 3, 2.4)

In [21]:
foo_3.bar=4.0


LoadError: setfield! immutable struct of type Foo cannot be changed

In [23]:
struct OrderedPair
           x::Real
           y::Real
           function OrderedPair(x, y)
               x > y && error("Arguments out of order.")
               return new(x, y)
           end
       end


In [24]:
methods(OrderedPair)

# 1 method for type constructor:
[1] OrderedPair(x, y) in Main at In[23]:4

In [25]:
op=OrderedPair(3,4)

OrderedPair(3, 4)

In [26]:
op=OrderedPair(5,4)

LoadError: Arguments out of order.

In [27]:
mutable struct Point{T <: Real}
           x::T
           y::T
       end


In [28]:
p1=Point{Float64}(2,5)

Point{Float64}(2.0, 5.0)

In [29]:
write(stdout, "Hello, world.");

Hello, world.

In [35]:
f = open("hello.txt")

IOStream(<file hello.txt>)

In [36]:
readlines(f)


1-element Array{String,1}:
 "Hello, World."

In [38]:
f = open("hello.txt", "a")



IOStream(<file hello.txt>)

In [39]:
write(f, "Hello again.\n");

In [41]:
open("hello.txt", "a") do f
           write(f, "I lied, one more line...\n");
       end


25

In [42]:
module MyModule
       struct MyType
           x
       end
       foo(x) = 2x
       const bar = 1.2
       end


Main.MyModule

In [45]:
MyType()


LoadError: UndefVarError: MyType not defined

In [46]:
MyModule.MyType(false)

Main.MyModule.MyType(false)

In [47]:
MyModule.foo(1)

2

In [48]:
MyModule.bar

1.2

In [54]:
#You can nest modules inside of each other:
module Parent
       module Utils
       double(x) = 2x
       end  # module Utils
       quadruple(x) = Utils.double(Utils.double(x))
    end  # module Parent





Main.Parent

In [55]:
Parent.quadruple(2)

8

In [57]:
# There are also two keywords for loading modules as libraries. Observe the behavior of the following two cases:

module ParentImport
       module Utils
       double(x) = 2x
       end  # module Utils
       module Useful
       import ..Utils
       quadruple(x) = Utils.double(Utils.double(x))
       end
end 



Main.ParentImport

In [58]:
module ParentUsing
       module Utils
       double(x) = 2x
       export double
       end  # module Utils
       using .Utils
       quadruple(x) = double(double(x))
   end 


Main.ParentUsing

In [60]:
using SparseArrays
I = [1, 1, 2, 2, 3, 3, 3, 4];
J = [1, 2, 2, 4, 3, 4, 5, 6];
V = rand(8);
D = sparse(I, J, V)


4×6 SparseMatrixCSC{Float64,Int64} with 8 stored entries:
  [1, 1]  =  0.969933
  [1, 2]  =  0.42462
  [2, 2]  =  0.482595
  [3, 3]  =  0.953901
  [2, 4]  =  0.221671
  [3, 4]  =  0.974508
  [3, 5]  =  0.00509282
  [4, 6]  =  0.616632

In [62]:
# `sum`: An easy enough function to understand


In [65]:
using BenchmarkTools
a=rand(10^7)

┌ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
└ @ Base loading.jl:1278


10000000-element Array{Float64,1}:
 0.8902569661528372
 0.41063690818834164
 0.629829161071565
 0.6369086795619736
 0.5703239451351725
 0.2461176187505283
 0.41987638398847316
 0.27018685922541197
 0.8196681437711337
 0.06070863541874916
 0.933240081147207
 0.7015046816846569
 0.409073174928793
 ⋮
 0.9129015467379547
 0.3821911401236133
 0.8894074873385913
 0.0338593812978516
 0.30172054581233865
 0.5424132842893878
 0.8477550066296968
 0.8721046831441033
 0.6822314139547909
 0.9590110111474743
 0.5822799302072093
 0.5339827158387864

In [67]:
@time sum(a)

  0.005151 seconds (1 allocation: 16 bytes)


5.000608695452001e6

In [68]:
function mysum_fast(A)
    s = 0.0
    for a in A
        @fastmath s += a
    end
    s
end

mysum_fast (generic function with 1 method)

In [72]:
j_fast = @benchmark mysum_fast($a)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     4.400 ms (0.00% GC)
  median time:      4.940 ms (0.00% GC)
  mean time:        4.947 ms (0.00% GC)
  maximum time:     5.457 ms (0.00% GC)
  --------------
  samples:          1011
  evals/sample:     1

In [70]:
function mysum_noassoc(A)
    s = 0.0
    for a in A
         s += a
    end
    s
end

mysum_noassoc (generic function with 1 method)

In [73]:
j_slow = @benchmark mysum_noassoc($a)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     11.595 ms (0.00% GC)
  median time:      11.770 ms (0.00% GC)
  mean time:        11.781 ms (0.00% GC)
  maximum time:     13.903 ms (0.00% GC)
  --------------
  samples:          425
  evals/sample:     1